### ISSUE TITLE
请问大神知道怎么用caffe做一维非图像数据的分类吗

### ISSUE THREAD

**Issue by gongyy** [frombeijingwithlove/dlcv_for_beginners#1]
请问大神知道怎么用caffe做一维非图像数据的分类吗

**Comment by frombeijingwithlove** [comment]
@gongyy 下边算不算一个“一维”的例子
https://github.com/frombeijingwithlove/dlcv_for_beginners/tree/master/chap7/caffe
用caffe做平面上坐标点分类的问题
