### ISSUE TITLE
第八章mxnet版本的mnist识别accuracy一直很低，而且不变

### ISSUE THREAD

**Issue by aikudexiaohai** [frombeijingwithlove/dlcv_for_beginners#10]
第八章mxnet版本的mnist识别accuracy一直很低，而且不变，我用的nxnet1.0.1版本，这是怎么回事

**Comment by aikudexiaohai** [comment]
还有就是我觉得mxnet的坑比较多，那还有学习nxnet的必要吗

**Comment by frombeijingwithlove** [comment]
这个问题 #6 也有提到，春节前较忙，有时间我也下载个最新版mxnet试一试，我个人已经弃坑mxnet很久了……所以不太清楚现在mxnet到底改进得怎么样了

**Comment by waldstein1983** [comment]
我也按照readme测试了第8章mxnet的代码，train之后在运行recognize_digit.py时，结果都识别为1
我运行的命令为：
python recognize_digit.py ../data/mnist/test/
得到结果是：
/usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/module/base_module.py:65: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
Predicted digit for ../data/mnist/val/000371_7.jpg is 1
Predicted digit for ../data/mnist/val/004634_4.jpg is 1
Predicted digit for ../data/mnist/val/005589_2.jpg is 1
Predicted digit for ../data/mnist/val/002725_6.jpg is 1
Predicted digit for ../data/mnist/val/003039_3.jpg is 1
Predicted digit for ../data/mnist/val/007156_5.jpg is 1
...........
...........
请问是不是我的姿势不对？

**Comment by dvlee1024** [comment]
遇到同样的问题

**Comment by aikudexiaohai** [comment]
一年了，我又回来了，今天终于解决了。在conv1和conv2之后加上relu层就可以了
