### ISSUE TITLE
第8章caffe版本模型训练好后测试发生 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by waldstein1983** [frombeijingwithlove/dlcv_for_beginners#12]
$ python recognize_digit.py ../data/test.txt 
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0205 15:06:08.584481 14628 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0205 15:06:08.584520 14628 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0205 15:06:08.584525 14628 _caffe.cpp:142] Net('lenet.prototxt', 1, weights='mnist_lenet_iter_36000.caffemodel')
I0205 15:06:08.586066 14628 net.cpp:51] Initializing net from parameters: 

I0205 15:06:08.586148 14628 layer_factory.hpp:77] Creating layer data
I0205 15:06:08.586163 14628 net.cpp:84] Creating Layer data
I0205 15:06:08.586174 14628 net.cpp:380] data -> data
I0205 15:06:08.586195 14628 net.cpp:122] Setting up data
I0205 15:06:08.586206 14628 net.cpp:129] Top shape: 64 1 28 28 (50176)
I0205 15:06:08.586211 14628 net.cpp:137] Memory required for data: 200704
I0205 15:06:08.586216 14628 layer_factory.hpp:77] Creating layer conv1
I0205 15:06:08.586227 14628 net.cpp:84] Creating Layer conv1
I0205 15:06:08.586233 14628 net.cpp:406] conv1 <- data
I0205 15:06:08.586241 14628 net.cpp:380] conv1 -> conv1
I0205 15:06:08.586324 14628 net.cpp:122] Setting up conv1
I0205 15:06:08.586334 14628 net.cpp:129] Top shape: 64 20 24 24 (737280)
I0205 15:06:08.586339 14628 net.cpp:137] Memory required for data: 3149824
I0205 15:06:08.586351 14628 layer_factory.hpp:77] Creating layer pool1
I0205 15:06:08.586361 14628 net.cpp:84] Creating Layer pool1
I0205 15:06:08.586367 14628 net.cpp:406] pool1 <- conv1
I0205 15:06:08.586374 14628 net.cpp:380] pool1 -> pool1
I0205 15:06:08.586387 14628 net.cpp:122] Setting up pool1
I0205 15:06:08.586395 14628 net.cpp:129] Top shape: 64 20 12 12 (184320)
I0205 15:06:08.586400 14628 net.cpp:137] Memory required for data: 3887104
I0205 15:06:08.586405 14628 layer_factory.hpp:77] Creating layer conv2
I0205 15:06:08.586416 14628 net.cpp:84] Creating Layer conv2
I0205 15:06:08.586421 14628 net.cpp:406] conv2 <- pool1
I0205 15:06:08.586428 14628 net.cpp:380] conv2 -> conv2
I0205 15:06:08.586645 14628 net.cpp:122] Setting up conv2
I0205 15:06:08.586658 14628 net.cpp:129] Top shape: 64 50 8 8 (204800)
I0205 15:06:08.586663 14628 net.cpp:137] Memory required for data: 4706304
I0205 15:06:08.586673 14628 layer_factory.hpp:77] Creating layer pool2
I0205 15:06:08.586683 14628 net.cpp:84] Creating Layer pool2
I0205 15:06:08.586688 14628 net.cpp:406] pool2 <- conv2
I0205 15:06:08.586696 14628 net.cpp:380] pool2 -> pool2
I0205 15:06:08.586706 14628 net.cpp:122] Setting up pool2
I0205 15:06:08.586714 14628 net.cpp:129] Top shape: 64 50 4 4 (51200)
I0205 15:06:08.586719 14628 net.cpp:137] Memory required for data: 4911104
I0205 15:06:08.586725 14628 layer_factory.hpp:77] Creating layer ip1
I0205 15:06:08.586735 14628 net.cpp:84] Creating Layer ip1
I0205 15:06:08.586740 14628 net.cpp:406] ip1 <- pool2
I0205 15:06:08.586747 14628 net.cpp:380] ip1 -> ip1
I0205 15:06:08.589907 14628 net.cpp:122] Setting up ip1
I0205 15:06:08.589939 14628 net.cpp:129] Top shape: 64 500 (32000)
I0205 15:06:08.589944 14628 net.cpp:137] Memory required for data: 5039104
I0205 15:06:08.589962 14628 layer_factory.hpp:77] Creating layer relu1
I0205 15:06:08.589977 14628 net.cpp:84] Creating Layer relu1
I0205 15:06:08.589983 14628 net.cpp:406] relu1 <- ip1
I0205 15:06:08.589992 14628 net.cpp:367] relu1 -> ip1 (in-place)
I0205 15:06:08.590001 14628 net.cpp:122] Setting up relu1
I0205 15:06:08.590006 14628 net.cpp:129] Top shape: 64 500 (32000)
I0205 15:06:08.590013 14628 net.cpp:137] Memory required for data: 5167104
I0205 15:06:08.590018 14628 layer_factory.hpp:77] Creating layer ip2
I0205 15:06:08.590028 14628 net.cpp:84] Creating Layer ip2
I0205 15:06:08.590034 14628 net.cpp:406] ip2 <- ip1
I0205 15:06:08.590040 14628 net.cpp:380] ip2 -> ip2
I0205 15:06:08.590100 14628 net.cpp:122] Setting up ip2
I0205 15:06:08.590107 14628 net.cpp:129] Top shape: 64 10 (640)
I0205 15:06:08.590112 14628 net.cpp:137] Memory required for data: 5169664
I0205 15:06:08.590119 14628 layer_factory.hpp:77] Creating layer prob
I0205 15:06:08.590127 14628 net.cpp:84] Creating Layer prob
I0205 15:06:08.590133 14628 net.cpp:406] prob <- ip2
I0205 15:06:08.590142 14628 net.cpp:380] prob -> prob
I0205 15:06:08.590152 14628 net.cpp:122] Setting up prob
I0205 15:06:08.590160 14628 net.cpp:129] Top shape: 64 10 (640)
I0205 15:06:08.590165 14628 net.cpp:137] Memory required for data: 5172224
I0205 15:06:08.590171 14628 net.cpp:200] prob does not need backward computation.
I0205 15:06:08.590178 14628 net.cpp:200] ip2 does not need backward computation.
I0205 15:06:08.590183 14628 net.cpp:200] relu1 does not need backward computation.
I0205 15:06:08.590186 14628 net.cpp:200] ip1 does not need backward computation.
I0205 15:06:08.590191 14628 net.cpp:200] pool2 does not need backward computation.
I0205 15:06:08.590196 14628 net.cpp:200] conv2 does not need backward computation.
I0205 15:06:08.590201 14628 net.cpp:200] pool1 does not need backward computation.
I0205 15:06:08.590206 14628 net.cpp:200] conv1 does not need backward computation.
I0205 15:06:08.590212 14628 net.cpp:200] data does not need backward computation.
I0205 15:06:08.590217 14628 net.cpp:242] This network produces output prob
I0205 15:06:08.590227 14628 net.cpp:255] Network initialization done.
I0205 15:06:08.592061 14628 net.cpp:744] Ignoring source layer mnist
I0205 15:06:08.592398 14628 net.cpp:744] Ignoring source layer loss
Traceback (most recent call last):
  File "recognize_digit.py", line 23, in <module>
    image = cv2.imread(imgpath, cv2.IMREAD_GRAYSCALE).astype(np.float) - MEAN
AttributeError: 'NoneType' object has no attribute 'astype'

请帮忙看看是怎么回事？

**Comment by frombeijingwithlove** [comment]
感觉是图片路径不对，cv2默认读取不到的时候就返回None
