### ISSUE TITLE
Change layer name after training

### ISSUE THREAD

**Issue by liangzelang** [frombeijingwithlove/dlcv_for_beginners#2]
your work on model fusion is great , and give me more inspiration. however ,there is a problem ,you change your layer name after training odd/even caffemodel,  e.g, your odd caffemodel conv1 layer name is 'conv1', after your change, this layer name is 'odd/conv1' , it will be re-trained because of caffe rules（If we provide the weights argument to the caffe train command, the pretrained weights will be loaded into our model, **matching layers by name**， see [here](http://caffe.berkeleyvision.org/gathered/examples/finetune_flickr_style.html)）. So if you change all the layers' name, your odd/even caffemodels can't have no usage.  In fact , your fusion model is just train from scratch.

I don't know is it right , so I hope you can give me some advice.

**Comment by frombeijingwithlove** [comment]
The fusion is done by 
https://github.com/frombeijingwithlove/dlcv_for_beginners/blob/master/random_bonus/multiple_models_fusion_caffe/fuse_model.py
line 19, weights are explicitly copied from seperate model
