### ISSUE TITLE
这里的label为什么要除以2呢?岂不是label都错了?

### ISSUE THREAD

**Issue by hkxIron** [frombeijingwithlove/dlcv_for_beginners#3]
https://github.com/frombeijingwithlove/dlcv_for_beginners/blob/196205ac0e9fefae7c5ab689455568d73373d9d3/random_bonus/multiple_models_fusion_caffe/gen_img_list.py#L20

**Comment by frombeijingwithlove** [comment]
因为对于单独的奇/偶数模型来说就是个五分类问题，所以不需要大于4的label
