### ISSUE TITLE
4.1.4 卷积情况下的权值数量

### ISSUE THREAD

**Issue by YanShuang17** [frombeijingwithlove/dlcv_for_beginners#4]
文中说卷积情况下，卷积核大小是2X2=4，一共是4x9=36个权值，但因为卷积操作是参数共享的，所以是否这里的权值参数数量只有2X2=4，而不是36呢？

**Comment by frombeijingwithlove** [comment]
“共享”一般指的是在当前通道内共享，通道间共享似乎没有见到过，所以是2x2x9
