### ISSUE TITLE
29页一处错误

### ISSUE THREAD

**Issue by HOUpu** [frombeijingwithlove/dlcv_for_beginners#8]
公式（2-9）上面：
则**u**在**v**上的投影长度为**u**的长度都是|**u**|cos(θ)
是不是应该改成 则**u**在**v**上的投影长度是|**u**|cos(θ)

**Comment by frombeijingwithlove** [comment]
确实是，已经在勘误表中更新，非常感谢！

**Comment by HOUpu** [comment]
90页公式3-5 求权值数好像不对
